### ISSUE TITLE
Could't login

### ISSUE THREAD

**Issue by Gusted** [lesander/magister-calendar#43] opened 2019-01-06 22:10 UTC
Hey, I was updating the appointements when this happend:
[!] 23:9:32 Could not login to magister. {"foutcode":"4N3NZYR","omschrijving":"Er is een onbekende fout opgetreden."}

It's wierd, because i tested te login details and it should work can someone help me?

**Comment by jvdoorn** [comment] 2019-01-06 22:14
Hey there!

Magister updated their authentication methods recently, I ran into this issue myself as well. My fork of the repository should fix this issue, you can check it out here: https://github.com/Argetan/magister-calendar

Make sure to run `npm update` if you are still having issues.

My fork comes with a couple other improvements (or at least I think they are) as well. I created a pull request but @lesander hasn't approved the changes yet (#39).

Let me know if you still run into any issues!

**Comment by Gusted** [comment] 2019-01-06 22:39
i still got an error because 'getSchools is'nt an function'

**Comment by jvdoorn** [comment] 2019-01-06 22:40
Did you run `npm update`? If so what does `npm view magister.js version` give you?

**Comment by Gusted** [comment] 2019-01-06 22:51
2.0.0-alpha

**Comment by jvdoorn** [comment] 2019-01-06 23:01
Are you sure it doesn't say `2.0.0-alpha.4`? If it does say `2.0.0-alpha.4` then I'm going to need the log file to see where it goes wrong. Also please check if your branch is up-to-date (`git status`) and if your remote is set correctly (`git remote show origin`), the FETCH URL should be `https://github.com/Argetan/magister-calendar.git`.

**Comment by Gusted** [comment] 2019-01-06 23:56
Im sure of that but it's when npm update it node.js that crash

**Comment by clrxbl** [comment] 2019-01-07 07:13
@Argetan Your repository doesn't seem to be working for me either.
[!] 8:12:42 Could not login to magister. {}

With debug mode enabled, the debug folder is empty, there's no extra error and I'm running 2.0.0-alpha.4

**Comment by jvdoorn** [comment] 2019-01-07 11:00
Which version of Node are you running? I'm running `v8.10.0` so you could try updating Node and then running `npm install` again.

**Comment by jvdoorn** [comment] 2019-01-07 15:21
I pushed an update to my branch that should print out the proper error message, could you check it out and tell me what error it gives @clrxbl ?

**Comment by clrxbl** [comment] 2019-01-07 15:24
Running v8.11.1 

[!] 16:24:8 Could not login to magister: "Cannot read property 'name' of undefined"

**Comment by jvdoorn** [comment] 2019-01-07 15:33
It appears that it didn't find your school. At some point the program says:
`Looking for schools matching XXX`
Does `XXX` match the first part of your schools URL (`https://XXX.magister.net`)?

**Comment by clrxbl** [comment] 2019-01-07 15:37
Yes, I've used the same link for years and it hasn't changed.

**Comment by jvdoorn** [comment] 2019-01-07 15:43
Alright, I think I fixed it, could you check out the latest version on my master branch?

**Comment by clrxbl** [comment] 2019-01-07 15:46
Same error

**Comment by jvdoorn** [comment] 2019-01-07 16:09
Alright, we determined what the problem is over Discord (the first part of the url can't always be used to look up a school). I will fix this issue a.s.a.p.

**Comment by jvdoorn** [comment] 2019-01-07 18:21
Alright, the authentication issue has been fixed. You can check out my repository's master branch for the changes.

**Comment by CemreSuler** [comment] 2019-01-11 10:27
I have the same problem, I couldn't fix it by using Argetan's code because I have my own fork. Argetan could you tell me what you did to fix it, so I can apply the changes to my own version?

**Comment by jvdoorn** [comment] 2019-01-11 12:45
If you make your fork available on Github I could have a look if it can be merged into mine. If not, the login issue can be fixed by updating `magister.js` to the latest version (`2.0.0-alpha.4`). This will break a majority of the code in `MagisterCalendar`, you'll have to fix the errors one by one (mostly functions that have become properties). You can have a look at the [diff](https://github.com/lesander/magister-calendar/pull/39/files?utf8=%E2%9C%93&diff=unified&w=1) of my pull request which should give you an idea of what has to be changed. Do note however that my PR also adds a couple features so not all changes are related to the login issue.

**Comment by jvdoorn** [comment] 2019-01-12 13:34
People who couldn't log in due to an `Invalid username` should check out the latest version of my branch. Updating `magister.js` from `2.0.0-alpha.4` to `2.0.0-alpha.5` fixes the issue. Make sure to run `npm update` when checking out my branch.

**Closed as completed** 2019-01-26 11:05 UTC
